/**
 * AES-128 / AES-256, CBC and single-block ECB — FIPS 197, pure TS.
 *
 * What names each piece:
 * - CBC decryption with a 16-byte IV prefix: §7.6.3.2 Algorithm 1 (AESV2,
 *   AES-128) and §7.6.3.3 Algorithm 1.A (AESV3, AES-256) — "the
 *   initialization vector is a 16-byte random number that is stored as
 *   the first 16 bytes of the encrypted stream or string".
 * - CBC *encryption* with no padding: §7.6.4.3.4 Algorithm 2.B step (b)
 *   — the revision-6 hash iterates AES-128-CBC encryption, so decryption
 *   alone is not enough.
 * - CBC decryption with no padding: §7.6.4.3.3 Algorithm 2.A steps (d)/(e)
 *   — the OE/UE strings decrypt "using AES-256 in CBC mode with no
 *   padding and an initialization vector of zero".
 * - Single-block ECB decryption: Algorithm 2.A step (f) / §7.6.4.4.12
 *   Algorithm 13 — the 16-byte Perms string.
 *
 * Pure TS for the same reason as `filter/inflate.ts` (ADR-0003): the
 * runtime surface stays engine-independent (WebCrypto has no no-padding
 * CBC and no ECB). The tests replay every operation through node:crypto
 * as a differential oracle.
 */

// FIPS 197 §5.1.1 — the S-box, and tables derived from it at module load.
const SBOX = new Uint8Array(256);
const INV_SBOX = new Uint8Array(256);
{
  // Generate the S-box from the affine transform over GF(2^8) — data, not
  // magic: p runs over the multiplicative group generated by 0x03.
  let p = 1;
  let q = 1;
  do {
    p = p ^ ((p << 1) & 0xff) ^ (p & 0x80 ? 0x1b : 0);
    q ^= q << 1;
    q ^= q << 2;
    q ^= q << 4;
    q &= 0xff;
    if (q & 0x80) {
      q ^= 0x09;
    }
    const s =
      q ^
      ((q << 1) | (q >>> 7)) ^
      ((q << 2) | (q >>> 6)) ^
      ((q << 3) | (q >>> 5)) ^
      ((q << 4) | (q >>> 4)) ^
      0x63;
    SBOX[p] = s & 0xff;
  } while (p !== 1);
  SBOX[0] = 0x63;
  for (let i = 0; i < 256; i += 1) {
    INV_SBOX[SBOX[i] as number] = i;
  }
}

/** GF(2^8) multiply (FIPS 197 §4.2). */
function gmul(a: number, b: number): number {
  let result = 0;
  let x = a;
  let y = b;
  while (y > 0) {
    if (y & 1) {
      result ^= x;
    }
    x = (x << 1) ^ (x & 0x80 ? 0x11b : 0);
    y >>>= 1;
  }
  return result & 0xff;
}

/** FIPS 197 §5.2 — key expansion; returns (rounds+1) × 16 bytes. */
function expandKey(key: Uint8Array): { schedule: Uint8Array; rounds: number } {
  const nk = key.length / 4; // 4 (AES-128) or 8 (AES-256)
  if (key.length !== 16 && key.length !== 32) {
    throw new RangeError(`AES key shall be 16 or 32 bytes, got ${key.length}`);
  }
  const rounds = nk + 6;
  const schedule = new Uint8Array((rounds + 1) * 16);
  schedule.set(key);
  let rcon = 1;
  for (let i = nk * 4; i < schedule.length; i += 4) {
    let t0 = schedule[i - 4] as number;
    let t1 = schedule[i - 3] as number;
    let t2 = schedule[i - 2] as number;
    let t3 = schedule[i - 1] as number;
    const word = i / 4;
    if (word % nk === 0) {
      // RotWord + SubWord + Rcon
      const r0 = SBOX[t1] as number;
      const r1 = SBOX[t2] as number;
      const r2 = SBOX[t3] as number;
      const r3 = SBOX[t0] as number;
      t0 = r0 ^ rcon;
      t1 = r1;
      t2 = r2;
      t3 = r3;
      rcon = gmul(rcon, 2);
    } else if (nk === 8 && word % nk === 4) {
      // AES-256 extra SubWord
      t0 = SBOX[t0] as number;
      t1 = SBOX[t1] as number;
      t2 = SBOX[t2] as number;
      t3 = SBOX[t3] as number;
    }
    schedule[i] = (schedule[i - nk * 4] as number) ^ t0;
    schedule[i + 1] = (schedule[i - nk * 4 + 1] as number) ^ t1;
    schedule[i + 2] = (schedule[i - nk * 4 + 2] as number) ^ t2;
    schedule[i + 3] = (schedule[i - nk * 4 + 3] as number) ^ t3;
  }
  return { schedule, rounds };
}

/** Encrypt one 16-byte block in place-free style (FIPS 197 §5.1). */
function encryptBlock(
  schedule: Uint8Array,
  rounds: number,
  input: Uint8Array,
  offset: number,
  out: Uint8Array,
  outOffset: number,
): void {
  const state = new Uint8Array(16);
  for (let i = 0; i < 16; i += 1) {
    state[i] = (input[offset + i] as number) ^ (schedule[i] as number);
  }
  for (let round = 1; round <= rounds; round += 1) {
    // SubBytes + ShiftRows
    const t = new Uint8Array(16);
    for (let c = 0; c < 4; c += 1) {
      t[c * 4] = SBOX[state[c * 4] as number] as number;
      t[c * 4 + 1] = SBOX[state[((c + 1) % 4) * 4 + 1] as number] as number;
      t[c * 4 + 2] = SBOX[state[((c + 2) % 4) * 4 + 2] as number] as number;
      t[c * 4 + 3] = SBOX[state[((c + 3) % 4) * 4 + 3] as number] as number;
    }
    if (round < rounds) {
      // MixColumns
      for (let c = 0; c < 4; c += 1) {
        const a0 = t[c * 4] as number;
        const a1 = t[c * 4 + 1] as number;
        const a2 = t[c * 4 + 2] as number;
        const a3 = t[c * 4 + 3] as number;
        state[c * 4] = gmul(a0, 2) ^ gmul(a1, 3) ^ a2 ^ a3;
        state[c * 4 + 1] = a0 ^ gmul(a1, 2) ^ gmul(a2, 3) ^ a3;
        state[c * 4 + 2] = a0 ^ a1 ^ gmul(a2, 2) ^ gmul(a3, 3);
        state[c * 4 + 3] = gmul(a0, 3) ^ a1 ^ a2 ^ gmul(a3, 2);
      }
    } else {
      state.set(t);
    }
    // AddRoundKey
    for (let i = 0; i < 16; i += 1) {
      state[i] = (state[i] as number) ^ (schedule[round * 16 + i] as number);
    }
  }
  out.set(state, outOffset);
}

/** Decrypt one 16-byte block (FIPS 197 §5.3, equivalent inverse cipher). */
function decryptBlock(
  schedule: Uint8Array,
  rounds: number,
  input: Uint8Array,
  offset: number,
  out: Uint8Array,
  outOffset: number,
): void {
  const state = new Uint8Array(16);
  for (let i = 0; i < 16; i += 1) {
    state[i] = (input[offset + i] as number) ^ (schedule[rounds * 16 + i] as number);
  }
  for (let round = rounds - 1; round >= 0; round -= 1) {
    // InvShiftRows + InvSubBytes
    const t = new Uint8Array(16);
    for (let c = 0; c < 4; c += 1) {
      t[c * 4] = INV_SBOX[state[c * 4] as number] as number;
      t[c * 4 + 1] = INV_SBOX[state[((c + 3) % 4) * 4 + 1] as number] as number;
      t[c * 4 + 2] = INV_SBOX[state[((c + 2) % 4) * 4 + 2] as number] as number;
      t[c * 4 + 3] = INV_SBOX[state[((c + 1) % 4) * 4 + 3] as number] as number;
    }
    // AddRoundKey
    for (let i = 0; i < 16; i += 1) {
      t[i] = (t[i] as number) ^ (schedule[round * 16 + i] as number);
    }
    if (round > 0) {
      // InvMixColumns
      for (let c = 0; c < 4; c += 1) {
        const a0 = t[c * 4] as number;
        const a1 = t[c * 4 + 1] as number;
        const a2 = t[c * 4 + 2] as number;
        const a3 = t[c * 4 + 3] as number;
        state[c * 4] = gmul(a0, 14) ^ gmul(a1, 11) ^ gmul(a2, 13) ^ gmul(a3, 9);
        state[c * 4 + 1] = gmul(a0, 9) ^ gmul(a1, 14) ^ gmul(a2, 11) ^ gmul(a3, 13);
        state[c * 4 + 2] = gmul(a0, 13) ^ gmul(a1, 9) ^ gmul(a2, 14) ^ gmul(a3, 11);
        state[c * 4 + 3] = gmul(a0, 11) ^ gmul(a1, 13) ^ gmul(a2, 9) ^ gmul(a3, 14);
      }
    } else {
      state.set(t);
    }
  }
  out.set(state, outOffset);
}

/** CBC encrypt with no padding (Algorithm 2.B step b; input length must be a multiple of 16). */
export function aesCbcEncryptNoPad(key: Uint8Array, iv: Uint8Array, data: Uint8Array): Uint8Array {
  if (data.length % 16 !== 0) {
    throw new RangeError(
      `no-padding CBC input shall be a multiple of 16 bytes, got ${data.length}`,
    );
  }
  const { schedule, rounds } = expandKey(key);
  const out = new Uint8Array(data.length);
  const block = new Uint8Array(16);
  let prev = iv;
  for (let i = 0; i < data.length; i += 16) {
    for (let j = 0; j < 16; j += 1) {
      block[j] = (data[i + j] as number) ^ (prev[j] as number);
    }
    encryptBlock(schedule, rounds, block, 0, out, i);
    prev = out.subarray(i, i + 16);
  }
  return out;
}

/** CBC decrypt with no padding (Algorithm 2.A steps d/e; input length must be a multiple of 16). */
export function aesCbcDecryptNoPad(key: Uint8Array, iv: Uint8Array, data: Uint8Array): Uint8Array {
  if (data.length % 16 !== 0) {
    throw new RangeError(
      `no-padding CBC input shall be a multiple of 16 bytes, got ${data.length}`,
    );
  }
  const { schedule, rounds } = expandKey(key);
  const out = new Uint8Array(data.length);
  let prev = iv;
  for (let i = 0; i < data.length; i += 16) {
    decryptBlock(schedule, rounds, data, i, out, i);
    for (let j = 0; j < 16; j += 1) {
      out[i + j] = (out[i + j] as number) ^ (prev[j] as number);
    }
    prev = data.subarray(i, i + 16);
  }
  return out;
}

/**
 * Decrypt PDF content data: 16-byte IV prefix, CBC, PKCS#7 padding
 * (§7.6.3.2 / §7.6.3.3 — "the initialization vector … is stored as the
 * first 16 bytes of the encrypted stream or string").
 *
 * Returns null when the layout cannot be what those clauses describe
 * (shorter than IV + one block, not block-aligned, or padding outside
 * 1..16) — the caller decides how to name the failure; this module does
 * not know which object it is decrypting.
 */
export function aesDecryptIvPrefixed(key: Uint8Array, data: Uint8Array): Uint8Array | null {
  if (data.length < 32 || (data.length - 16) % 16 !== 0) {
    return null;
  }
  const plain = aesCbcDecryptNoPad(key, data.subarray(0, 16), data.subarray(16));
  const pad = plain[plain.length - 1] as number;
  if (pad < 1 || pad > 16) {
    return null;
  }
  return plain.subarray(0, plain.length - pad);
}

/** Decrypt one 16-byte block in ECB mode (Perms — Algorithm 2.A step f / Algorithm 13). */
export function aesEcbDecryptBlock(key: Uint8Array, block: Uint8Array): Uint8Array {
  if (block.length !== 16) {
    throw new RangeError(`ECB block shall be 16 bytes, got ${block.length}`);
  }
  const { schedule, rounds } = expandKey(key);
  const out = new Uint8Array(16);
  decryptBlock(schedule, rounds, block, 0, out, 0);
  return out;
}
