/**
 * Encrypted fixtures — frozen bytes produced by qpdf 11.9.0, an
 * INDEPENDENT implementation (GUARDS T-2: the library must not read only
 * what it writes; here it has no encryption side at all, ADR-0008).
 *
 * Frozen bytes are the exception this repository allows when hand-written
 * source is impossible (see tests/helpers/page-trees.ts on uc-oracle):
 * an encrypted fixture cannot be authored by hand, because /O, /U and
 * every string and stream are functions of a key derivation. What a
 * reviewer needs to see is the recipe, so the exact command is recorded
 * per fixture; regenerating produces different bytes (random IVs and
 * salts) but the same measured facts.
 *
 * All fixtures encrypt the same base document: a one-page file whose
 * content stream is "BT /F1 12 Tf 72 720 Td (Hello normative) Tj ET" and
 * whose catalog references << /Note (plain string payload) >> (the
 * reference exists so qpdf keeps the object — the first cut left it
 * unreferenced and qpdf silently dropped it from every fixture). The
 * recovery of those exact plaintext bytes is what the tests assert.
 */

const b64 = (s: string): Uint8Array => Uint8Array.from(atob(s), (c) => c.charCodeAt(0));

/** The unencrypted document every fixture encrypts (expected-plaintext reference). */
export const plainBase = b64(
  'JVBERi0xLjcKJb/3ov4KMSAwIG9iago8PCAvTm90ZUhvbGRlciAyIDAgUiAvUGFnZXMgMyAwIFIgL1R5cGUgL0NhdGFsb2cgPj4K' +
    'ZW5kb2JqCjIgMCBvYmoKPDwgL05vdGUgKHBsYWluIHN0cmluZyBwYXlsb2FkKSA+PgplbmRvYmoKMyAwIG9iago8PCAvQ291bnQg' +
    'MSAvS2lkcyBbIDQgMCBSIF0gL1R5cGUgL1BhZ2VzID4+CmVuZG9iago0IDAgb2JqCjw8IC9Db250ZW50cyA1IDAgUiAvTWVkaWFC' +
    'b3ggWyAwIDAgNjEyIDc5MiBdIC9QYXJlbnQgMyAwIFIgL1R5cGUgL1BhZ2UgPj4KZW5kb2JqCjUgMCBvYmoKPDwgL0xlbmd0aCA1' +
    'MyAvRmlsdGVyIC9GbGF0ZURlY29kZSA+PgpzdHJlYW0KeJxzClHQdzNUMDRSCElTMDcCIgOFkBQFDY/UnJx8hbz8otzEksyyVE2F' +
    'kCwF1xAuABscDM9lbmRzdHJlYW0KZW5kb2JqCnhyZWYKMCA2CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAxNSAwMDAwMCBu' +
    'IAowMDAwMDAwMDgyIDAwMDAwIG4gCjAwMDAwMDAxMzIgMDAwMDAgbiAKMDAwMDAwMDE5MSAwMDAwMCBuIAowMDAwMDAwMjgwIDAw' +
    'MDAwIG4gCnRyYWlsZXIgPDwgL1Jvb3QgMSAwIFIgL1NpemUgNiAvSUQgWzxiMzJjZDE4NDEzYjcyYjIyZmQ3MGVjNzI4Y2FiZTIz' +
    'MT48YjMyY2QxODQxM2I3MmIyMmZkNzBlYzcyOGNhYmUyMzE+XSA+PgpzdGFydHhyZWYKNDAzCiUlRU9GCg==',
);

/** V 1, R 2, RC4 40-bit. Recipe: `qpdf --allow-weak-crypto --encrypt "" "" 40 -- base.pdf out.pdf` */
export const rc4_40 = b64(
  'JVBERi0xLjcKJb/3ov4KMSAwIG9iago8PCAvTm90ZUhvbGRlciAyIDAgUiAvUGFnZXMgMyAwIFIgL1R5cGUgL0NhdGFsb2cgPj4K' +
    'ZW5kb2JqCjIgMCBvYmoKPDwgL05vdGUgPGY5ZmRkYzIwZjE2MmY1NzMyZGE4ZjQ3N2Q2NTQxMWM3YjY0YzZlNWM+ID4+CmVuZG9i' +
    'agozIDAgb2JqCjw8IC9Db3VudCAxIC9LaWRzIFsgNCAwIFIgXSAvVHlwZSAvUGFnZXMgPj4KZW5kb2JqCjQgMCBvYmoKPDwgL0Nv' +
    'bnRlbnRzIDUgMCBSIC9NZWRpYUJveCBbIDAgMCA2MTIgNzkyIF0gL1BhcmVudCAzIDAgUiAvVHlwZSAvUGFnZSA+PgplbmRvYmoK' +
    'NSAwIG9iago8PCAvRmlsdGVyIC9GbGF0ZURlY29kZSAvTGVuZ3RoIDUzID4+CnN0cmVhbQoutttTMsgrR1APlYIE1YoBfgRqQK+k' +
    'tjYtDO26XvuIPSeLAjf3mbqdYMHA+0cYq4KXlG3f/WVuZHN0cmVhbQplbmRvYmoKNiAwIG9iago8PCAvRmlsdGVyIC9TdGFuZGFy' +
    'ZCAvTGVuZ3RoIDQwIC9PIDwyMDU1Yzc1NmM3MmUxYWQ3MDI2MDhlODE5NmFjYWQ0NDdhZDMyZDE3Y2ZmNTgzMjM1ZjZkZDE1ZmVk' +
    'N2RhYjY3PiAvUCAtNCAvUiAyIC9VIDxjMmExNGUyMzEwNWMwY2Q3Mjc3MzdhNDc5MmMzNGNkNTc0OTE0MDc1NDU2ZTc3ZDY0NGUx' +
    'MWEzMTU5ZjQ3NmVjPiAvViAxID4+CmVuZG9iagp4cmVmCjAgNwowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwMTUgMDAwMDAg' +
    'biAKMDAwMDAwMDA4MiAwMDAwMCBuIAowMDAwMDAwMTUyIDAwMDAwIG4gCjAwMDAwMDAyMTEgMDAwMDAgbiAKMDAwMDAwMDMwMCAw' +
    'MDAwMCBuIAowMDAwMDAwNDIzIDAwMDAwIG4gCnRyYWlsZXIgPDwgL1Jvb3QgMSAwIFIgL1NpemUgNyAvSUQgWzxiMzJjZDE4NDEz' +
    'YjcyYjIyZmQ3MGVjNzI4Y2FiZTIzMT48NGIyZDBiNzMzNDlkMGEyNzM5NDg0NGQxZDExYWZhODc+XSAvRW5jcnlwdCA2IDAgUiA+' +
    'PgpzdGFydHhyZWYKNjI5CiUlRU9GCg==',
);

/** V 2, R 3, RC4 128-bit. Recipe: `qpdf --allow-weak-crypto --encrypt "" "" 128 -- base.pdf out.pdf` */
export const rc4_128 = b64(
  'JVBERi0xLjcKJb/3ov4KMSAwIG9iago8PCAvTm90ZUhvbGRlciAyIDAgUiAvUGFnZXMgMyAwIFIgL1R5cGUgL0NhdGFsb2cgPj4K' +
    'ZW5kb2JqCjIgMCBvYmoKPDwgL05vdGUgPDU1ZmI2ODlkZWQzNWVhMzM0OTg5MDQzMjQwOTM0MDJmMmM4NTRjMTI+ID4+CmVuZG9i' +
    'agozIDAgb2JqCjw8IC9Db3VudCAxIC9LaWRzIFsgNCAwIFIgXSAvVHlwZSAvUGFnZXMgPj4KZW5kb2JqCjQgMCBvYmoKPDwgL0Nv' +
    'bnRlbnRzIDUgMCBSIC9NZWRpYUJveCBbIDAgMCA2MTIgNzkyIF0gL1BhcmVudCAzIDAgUiAvVHlwZSAvUGFnZSA+PgplbmRvYmoK' +
    'NSAwIG9iago8PCAvRmlsdGVyIC9GbGF0ZURlY29kZSAvTGVuZ3RoIDUzID4+CnN0cmVhbQpcVq/sRXw+iBiQ4+lSevDc/+LywtJU' +
    'Yc/dDK3TImXkneEV1npS6NTNdwg19E8ijx8TmUc64WVuZHN0cmVhbQplbmRvYmoKNiAwIG9iago8PCAvRmlsdGVyIC9TdGFuZGFy' +
    'ZCAvTGVuZ3RoIDEyOCAvTyA8MzY0NTFiZDM5ZDc1M2I3YzFkMTA5MjJjMjhlNjY2NWFhNGYzMzUzZmIwMzQ4YjUzNjg5M2UzYjFk' +
    'YjVjNTc5Yj4gL1AgLTQgL1IgMyAvVSA8NzQwNzNkYzE1ZmNlYTJiZjdjMjYyNGQ1NTllMTJhYWYwMTIyNDU2YTkxYmFlNTEzNDI3' +
    'M2E2ZGIxMzRjODdjND4gL1YgMiA+PgplbmRvYmoKeHJlZgowIDcKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwMDE1IDAwMDAw' +
    'IG4gCjAwMDAwMDAwODIgMDAwMDAgbiAKMDAwMDAwMDE1MiAwMDAwMCBuIAowMDAwMDAwMjExIDAwMDAwIG4gCjAwMDAwMDAzMDAg' +
    'MDAwMDAgbiAKMDAwMDAwMDQyMyAwMDAwMCBuIAp0cmFpbGVyIDw8IC9Sb290IDEgMCBSIC9TaXplIDcgL0lEIFs8YjMyY2QxODQx' +
    'M2I3MmIyMmZkNzBlYzcyOGNhYmUyMzE+PGVkNTJlY2Y2Nzg0NTNlODE2YzNmZmY3Njc0NTYzYTYyPl0gL0VuY3J5cHQgNiAwIFIg' +
    'Pj4Kc3RhcnR4cmVmCjYzMAolJUVPRgo=',
);

/** V 2, R 3, RC4 128-bit, user password 'usr', owner 'own'. Recipe: `qpdf --allow-weak-crypto --encrypt "usr" "own" 128 -- base.pdf out.pdf` */
export const rc4_128_pw = b64(
  'JVBERi0xLjcKJb/3ov4KMSAwIG9iago8PCAvTm90ZUhvbGRlciAyIDAgUiAvUGFnZXMgMyAwIFIgL1R5cGUgL0NhdGFsb2cgPj4K' +
    'ZW5kb2JqCjIgMCBvYmoKPDwgL05vdGUgPGU2MzBkYzJhZDJmMGEzMmRhYWEyNTk2NmI2ZjQ4MTliZTRiMjhlNGU+ID4+CmVuZG9i' +
    'agozIDAgb2JqCjw8IC9Db3VudCAxIC9LaWRzIFsgNCAwIFIgXSAvVHlwZSAvUGFnZXMgPj4KZW5kb2JqCjQgMCBvYmoKPDwgL0Nv' +
    'bnRlbnRzIDUgMCBSIC9NZWRpYUJveCBbIDAgMCA2MTIgNzkyIF0gL1BhcmVudCAzIDAgUiAvVHlwZSAvUGFnZSA+PgplbmRvYmoK' +
    'NSAwIG9iago8PCAvRmlsdGVyIC9GbGF0ZURlY29kZSAvTGVuZ3RoIDUzID4+CnN0cmVhbQrUAVvPmUvSgZQKeEHoKO+Ub+nhRQvI' +
    'z8A8VD2D9qfb5Mz36DqlQ/Xe1jGU0EcbWNj3EJpmWmVuZHN0cmVhbQplbmRvYmoKNiAwIG9iago8PCAvRmlsdGVyIC9TdGFuZGFy' +
    'ZCAvTGVuZ3RoIDEyOCAvTyA8MzgzN2QyYzE5ZjdkNDViOGNkYzFhNGQ3NDZhNTk5NzBjZDQwMzE0ODMxYjI4NzUwZDUzYTExZTMx' +
    'Y2U5MzAwYT4gL1AgLTQgL1IgMyAvVSA8M2ZlMjJlM2M1NWI4NWVhZGM0ZDcxYWNjMWVjMTUyZWYwMTIyNDU2YTkxYmFlNTEzNDI3' +
    'M2E2ZGIxMzRjODdjND4gL1YgMiA+PgplbmRvYmoKeHJlZgowIDcKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwMDE1IDAwMDAw' +
    'IG4gCjAwMDAwMDAwODIgMDAwMDAgbiAKMDAwMDAwMDE1MiAwMDAwMCBuIAowMDAwMDAwMjExIDAwMDAwIG4gCjAwMDAwMDAzMDAg' +
    'MDAwMDAgbiAKMDAwMDAwMDQyMyAwMDAwMCBuIAp0cmFpbGVyIDw8IC9Sb290IDEgMCBSIC9TaXplIDcgL0lEIFs8YjMyY2QxODQx' +
    'M2I3MmIyMmZkNzBlYzcyOGNhYmUyMzE+PDllYjFkZGQ4ZWI4MzZlZWZjYWIzZGU3M2YxZmExMTIxPl0gL0VuY3J5cHQgNiAwIFIg' +
    'Pj4Kc3RhcnR4cmVmCjYzMAolJUVPRgo=',
);

/** V 4, R 4, crypt filter AESV2. Recipe: `qpdf --encrypt "" "" 128 --use-aes=y -- base.pdf out.pdf` */
export const aes128 = b64(
  'JVBERi0xLjcKJb/3ov4KMSAwIG9iago8PCAvTm90ZUhvbGRlciAyIDAgUiAvUGFnZXMgMyAwIFIgL1R5cGUgL0NhdGFsb2cgPj4K' +
    'ZW5kb2JqCjIgMCBvYmoKPDwgL05vdGUgPDE3NDEwNWI1NWNmM2MyM2ZiNjU3MTgzZjZhMTkxYTI2ZGI0NTk4OTNkYzUzM2ZiYTZm' +
    'NDdkY2U3ODFlZGU0MjhiMGZjYTA1ZTMzYmI3Mjc0NTA5NDQzZmEyY2FlNjIyZj4gPj4KZW5kb2JqCjMgMCBvYmoKPDwgL0NvdW50' +
    'IDEgL0tpZHMgWyA0IDAgUiBdIC9UeXBlIC9QYWdlcyA+PgplbmRvYmoKNCAwIG9iago8PCAvQ29udGVudHMgNSAwIFIgL01lZGlh' +
    'Qm94IFsgMCAwIDYxMiA3OTIgXSAvUGFyZW50IDMgMCBSIC9UeXBlIC9QYWdlID4+CmVuZG9iago1IDAgb2JqCjw8IC9GaWx0ZXIg' +
    'L0ZsYXRlRGVjb2RlIC9MZW5ndGggODAgPj4Kc3RyZWFtCj00GS59+fjA6IMal/b+jY955/BMTKsU5qL8KgKbR5Z40DzuBToydjId' +
    'bGl6msTAHJFYZa3QEPdlLx3Pyv9RuaB9Pcx/9V8NMK5XvgPXOHhcZW5kc3RyZWFtCmVuZG9iago2IDAgb2JqCjw8IC9DRiA8PCAv' +
    'U3RkQ0YgPDwgL0F1dGhFdmVudCAvRG9jT3BlbiAvQ0ZNIC9BRVNWMiAvTGVuZ3RoIDE2ID4+ID4+IC9GaWx0ZXIgL1N0YW5kYXJk' +
    'IC9MZW5ndGggMTI4IC9PIDwzNjQ1MWJkMzlkNzUzYjdjMWQxMDkyMmMyOGU2NjY1YWE0ZjMzNTNmYjAzNDhiNTM2ODkzZTNiMWRi' +
    'NWM1NzliPiAvUCAtNCAvUiA0IC9TdG1GIC9TdGRDRiAvU3RyRiAvU3RkQ0YgL1UgPDc0MDczZGMxNWZjZWEyYmY3YzI2MjRkNTU5' +
    'ZTEyYWFmMDEyMjQ1NmE5MWJhZTUxMzQyNzNhNmRiMTM0Yzg3YzQ+IC9WIDQgPj4KZW5kb2JqCnhyZWYKMCA3CjAwMDAwMDAwMDAg' +
    'NjU1MzUgZiAKMDAwMDAwMDAxNSAwMDAwMCBuIAowMDAwMDAwMDgyIDAwMDAwIG4gCjAwMDAwMDAyMDggMDAwMDAgbiAKMDAwMDAw' +
    'MDI2NyAwMDAwMCBuIAowMDAwMDAwMzU2IDAwMDAwIG4gCjAwMDAwMDA1MDYgMDAwMDAgbiAKdHJhaWxlciA8PCAvUm9vdCAxIDAg' +
    'UiAvU2l6ZSA3IC9JRCBbPGIzMmNkMTg0MTNiNzJiMjJmZDcwZWM3MjhjYWJlMjMxPjxiMzc0ZGMyYjE2N2JkMzdjODk0ODRhMTcz' +
    'ZWFmOWVjMz5dIC9FbmNyeXB0IDYgMCBSID4+CnN0YXJ0eHJlZgo4MDUKJSVFT0YK',
);

/** V 4, R 4, AESV2, user password 'usr', owner 'own'. Recipe: `qpdf --encrypt "usr" "own" 128 --use-aes=y -- base.pdf out.pdf` */
export const aes128_pw = b64(
  'JVBERi0xLjcKJb/3ov4KMSAwIG9iago8PCAvTm90ZUhvbGRlciAyIDAgUiAvUGFnZXMgMyAwIFIgL1R5cGUgL0NhdGFsb2cgPj4K' +
    'ZW5kb2JqCjIgMCBvYmoKPDwgL05vdGUgPDkyNTRhODJhMTYyYjJlN2ViZWNhNzQ1ODBhMDQ2NjczODM5ZmQ5NDI3ZmNlZjZhODI3' +
    'ZmZhOGZjNzFlZGYxZjQ4ZjVhZjBkYTI3NWU3NjQxNWYxMjY3Y2ExM2VmOGE2OD4gPj4KZW5kb2JqCjMgMCBvYmoKPDwgL0NvdW50' +
    'IDEgL0tpZHMgWyA0IDAgUiBdIC9UeXBlIC9QYWdlcyA+PgplbmRvYmoKNCAwIG9iago8PCAvQ29udGVudHMgNSAwIFIgL01lZGlh' +
    'Qm94IFsgMCAwIDYxMiA3OTIgXSAvUGFyZW50IDMgMCBSIC9UeXBlIC9QYWdlID4+CmVuZG9iago1IDAgb2JqCjw8IC9GaWx0ZXIg' +
    'L0ZsYXRlRGVjb2RlIC9MZW5ndGggODAgPj4Kc3RyZWFtCsE2ndFwVzo5y2Gf82xg9BOkbUNyL1Ja2EcRub5RJQRNgXgR09QaB3S4' +
    'aM8FOB19YzqJPHpB7SD1+f2si5RO6ATG09kHW6S2pAUYjHTZ1qr6ZW5kc3RyZWFtCmVuZG9iago2IDAgb2JqCjw8IC9DRiA8PCAv' +
    'U3RkQ0YgPDwgL0F1dGhFdmVudCAvRG9jT3BlbiAvQ0ZNIC9BRVNWMiAvTGVuZ3RoIDE2ID4+ID4+IC9GaWx0ZXIgL1N0YW5kYXJk' +
    'IC9MZW5ndGggMTI4IC9PIDwzODM3ZDJjMTlmN2Q0NWI4Y2RjMWE0ZDc0NmE1OTk3MGNkNDAzMTQ4MzFiMjg3NTBkNTNhMTFlMzFj' +
    'ZTkzMDBhPiAvUCAtNCAvUiA0IC9TdG1GIC9TdGRDRiAvU3RyRiAvU3RkQ0YgL1UgPDNmZTIyZTNjNTViODVlYWRjNGQ3MWFjYzFl' +
    'YzE1MmVmMDEyMjQ1NmE5MWJhZTUxMzQyNzNhNmRiMTM0Yzg3YzQ+IC9WIDQgPj4KZW5kb2JqCnhyZWYKMCA3CjAwMDAwMDAwMDAg' +
    'NjU1MzUgZiAKMDAwMDAwMDAxNSAwMDAwMCBuIAowMDAwMDAwMDgyIDAwMDAwIG4gCjAwMDAwMDAyMDggMDAwMDAgbiAKMDAwMDAw' +
    'MDI2NyAwMDAwMCBuIAowMDAwMDAwMzU2IDAwMDAwIG4gCjAwMDAwMDA1MDYgMDAwMDAgbiAKdHJhaWxlciA8PCAvUm9vdCAxIDAg' +
    'UiAvU2l6ZSA3IC9JRCBbPGIzMmNkMTg0MTNiNzJiMjJmZDcwZWM3MjhjYWJlMjMxPjw5MDU1YjI5MzQwMzk5ZmE0NDQ5NjhiMGFi' +
    'OGRjMzNiMT5dIC9FbmNyeXB0IDYgMCBSID4+CnN0YXJ0eHJlZgo4MDUKJSVFT0YK',
);

/** V 5, R 6, AESV3. Recipe: `qpdf --encrypt "" "" 256 -- base.pdf out.pdf` */
export const aes256 = b64(
  'JVBERi0xLjcKJb/3ov4KMSAwIG9iago8PCAvRXh0ZW5zaW9ucyA8PCAvQURCRSA8PCAvQmFzZVZlcnNpb24gLzEuNyAvRXh0ZW5z' +
    'aW9uTGV2ZWwgOCA+PiA+PiAvTm90ZUhvbGRlciAyIDAgUiAvUGFnZXMgMyAwIFIgL1R5cGUgL0NhdGFsb2cgPj4KZW5kb2JqCjIg' +
    'MCBvYmoKPDwgL05vdGUgPGQ3ZmUzNmJhNzcyYjRmZTNjYzkxZTg2ZmI0YzEwNzc1YzU3YzZiYjFlMjkwZDM1NGI1ZGQ1YTcxMDIw' +
    'ODEwYjNlODg0ZWE2OWE2YjE2ZDE1NjBlNTFiNmZmYmNmYzMyOD4gPj4KZW5kb2JqCjMgMCBvYmoKPDwgL0NvdW50IDEgL0tpZHMg' +
    'WyA0IDAgUiBdIC9UeXBlIC9QYWdlcyA+PgplbmRvYmoKNCAwIG9iago8PCAvQ29udGVudHMgNSAwIFIgL01lZGlhQm94IFsgMCAw' +
    'IDYxMiA3OTIgXSAvUGFyZW50IDMgMCBSIC9UeXBlIC9QYWdlID4+CmVuZG9iago1IDAgb2JqCjw8IC9GaWx0ZXIgL0ZsYXRlRGVj' +
    'b2RlIC9MZW5ndGggODAgPj4Kc3RyZWFtCoroYSs+aCwhJVwMfD0p7hWcxd1AJ6QhpDxz2k6S4EWrXICYYkUfyHn2obEA2k+lUDWd' +
    'wmHGC+bAbXowpaYnPYBPM1crYT1TkSQvMAy37RzRZW5kc3RyZWFtCmVuZG9iago2IDAgb2JqCjw8IC9DRiA8PCAvU3RkQ0YgPDwg' +
    'L0F1dGhFdmVudCAvRG9jT3BlbiAvQ0ZNIC9BRVNWMyAvTGVuZ3RoIDMyID4+ID4+IC9GaWx0ZXIgL1N0YW5kYXJkIC9MZW5ndGgg' +
    'MjU2IC9PIDxlZjA4NzZiNDI1Njk0ZTYwNDlkZmMyMmIzMzBhNTk1MTg5NTNlYTEzZTA2YjBiZTM3MjI2NjQ2MDg3YmU2OWM5ZWE4' +
    'MWI0NjIzZTY1NjBmZTA2MWZmM2E5MDc1NGEwNzA+IC9PRSA8OWJmNmNiMmY5YzllZWM1ODBjYjcwNzMwMTIzNzJiMDFiZWI4NWM2' +
    'OWVmNTQ0MmQ3OGRmNjI5ZGIwYzM5YzM0Yz4gL1AgLTQgL1Blcm1zIDw5MWNlMjJjNDkyNGY3YjkyNzFjZDliZGQ3OWE3OGUyYj4g' +
    'L1IgNiAvU3RtRiAvU3RkQ0YgL1N0ckYgL1N0ZENGIC9VIDxhZGE3YjJkNDMwNTIwOTI4NmU2YmVjNGY2NGRmZGMyZmJlMDExMWVh' +
    'MGE1NmNiNzIxMjg4NDkwMzY5NzQ2MzFlZTE2NzVjOGY1MmEwY2I2YTBmYWRhNTRjN2M3NWM5NzA+IC9VRSA8NmRiNzAyNGQzZWM2' +
    'OGEwYTY4NDQwNDQxMGE0ZDM3MTY5ZWVhNjVhODZhN2RkNGVkNWQxNDBlYjk1YjRjYTgzNz4gL1YgNSA+PgplbmRvYmoKeHJlZgow' +
    'IDcKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwMDE1IDAwMDAwIG4gCjAwMDAwMDAxNDggMDAwMDAgbiAKMDAwMDAwMDI3NCAw' +
    'MDAwMCBuIAowMDAwMDAwMzMzIDAwMDAwIG4gCjAwMDAwMDA0MjIgMDAwMDAgbiAKMDAwMDAwMDU3MiAwMDAwMCBuIAp0cmFpbGVy' +
    'IDw8IC9Sb290IDEgMCBSIC9TaXplIDcgL0lEIFs8YjMyY2QxODQxM2I3MmIyMmZkNzBlYzcyOGNhYmUyMzE+PGRmNzQ0ZjgxNmJj' +
    'MTA1ZjY4YmEyNzZmZTVkMmEyOTVhPl0gL0VuY3J5cHQgNiAwIFIgPj4Kc3RhcnR4cmVmCjExMTkKJSVFT0YK',
);

/** V 5, R 6, AESV3, user password 'usr', owner 'own'. Recipe: `qpdf --encrypt "usr" "own" 256 -- base.pdf out.pdf` */
export const aes256_pw = b64(
  'JVBERi0xLjcKJb/3ov4KMSAwIG9iago8PCAvRXh0ZW5zaW9ucyA8PCAvQURCRSA8PCAvQmFzZVZlcnNpb24gLzEuNyAvRXh0ZW5z' +
    'aW9uTGV2ZWwgOCA+PiA+PiAvTm90ZUhvbGRlciAyIDAgUiAvUGFnZXMgMyAwIFIgL1R5cGUgL0NhdGFsb2cgPj4KZW5kb2JqCjIg' +
    'MCBvYmoKPDwgL05vdGUgPDgxMmYzZGQ5OTE5NTBlZTIxNWZmNGIyZmU4ZjMxZDVmOWRhZDVmMTUxNTUyYWY2OGY4NDhkOTQzNzE1' +
    'MTI0NzhjZjU1MmM4MGYxMjgxNjk5NjNkYzUxMGRmNDU4OTA3Mz4gPj4KZW5kb2JqCjMgMCBvYmoKPDwgL0NvdW50IDEgL0tpZHMg' +
    'WyA0IDAgUiBdIC9UeXBlIC9QYWdlcyA+PgplbmRvYmoKNCAwIG9iago8PCAvQ29udGVudHMgNSAwIFIgL01lZGlhQm94IFsgMCAw' +
    'IDYxMiA3OTIgXSAvUGFyZW50IDMgMCBSIC9UeXBlIC9QYWdlID4+CmVuZG9iago1IDAgb2JqCjw8IC9GaWx0ZXIgL0ZsYXRlRGVj' +
    'b2RlIC9MZW5ndGggODAgPj4Kc3RyZWFtCpHyYSOc9FzTyIibRKS7R3GSQWcs5t00qkfNNk5SwvRnTW3LYqyDp7iwL0UmcEucnhUT' +
    '3hLDqr2Bqc0nOQSSvzoSWlb4JtZD2ctWItajA/gGZW5kc3RyZWFtCmVuZG9iago2IDAgb2JqCjw8IC9DRiA8PCAvU3RkQ0YgPDwg' +
    'L0F1dGhFdmVudCAvRG9jT3BlbiAvQ0ZNIC9BRVNWMyAvTGVuZ3RoIDMyID4+ID4+IC9GaWx0ZXIgL1N0YW5kYXJkIC9MZW5ndGgg' +
    'MjU2IC9PIDwxYmUyNTVmNzZlMTY3NzQ2NmViNzcyYmRhNWVkYTk3MmY1MjkwM2Q0NTVkZmFkZGMxNTcxNzNhN2NkOWUzZDEyOGZi' +
    'OWY2YTNkN2NhMWQ4YzdjY2IxYmYyNjg3NGFkNDg+IC9PRSA8YjQ2MDhkZmU4YjUyODAwOGFiYmQwMzUxNDhlYWFiMzI3M2FiZjIw' +
    'MjM2NDdkYTQ3MmUxNmM0ODUxZDUwYThlNz4gL1AgLTQgL1Blcm1zIDxlZmRiNGU5NmRjNDFhMGUxYjFiY2Y4NTU2NzFkMzM4YT4g' +
    'L1IgNiAvU3RtRiAvU3RkQ0YgL1N0ckYgL1N0ZENGIC9VIDxmNTQyZGNhNmNhNzhkNTRhODk4MDkwM2MxMDQ4ODg4ZThmMzEyNTZl' +
    'NTJhYmRlNjJlMGFiMWVmMTVjYWUwMjllYzcxMzUwNGFjYTZiNzgwM2MzYzBhZTQyN2QzYmYxZDE+IC9VRSA8NTEyMzgwY2UxOWY1' +
    'M2RiZjBmMjNhZjAzYjQ1YjU3ZmJhYjVjNzM5MDhhZTBkY2FkMDMyYzkxMGZlZDVlYTIyNz4gL1YgNSA+PgplbmRvYmoKeHJlZgow' +
    'IDcKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwMDE1IDAwMDAwIG4gCjAwMDAwMDAxNDggMDAwMDAgbiAKMDAwMDAwMDI3NCAw' +
    'MDAwMCBuIAowMDAwMDAwMzMzIDAwMDAwIG4gCjAwMDAwMDA0MjIgMDAwMDAgbiAKMDAwMDAwMDU3MiAwMDAwMCBuIAp0cmFpbGVy' +
    'IDw8IC9Sb290IDEgMCBSIC9TaXplIDcgL0lEIFs8YjMyY2QxODQxM2I3MmIyMmZkNzBlYzcyOGNhYmUyMzE+PDk0MTU0NjU2NWJl' +
    'MjliNTU1MmMyZjNjMDA0OWVmZDJhPl0gL0VuY3J5cHQgNiAwIFIgPj4Kc3RhcnR4cmVmCjExMTkKJSVFT0YK',
);

/** V 5, R 6, AESV3, objects compressed into object streams. Recipe: `qpdf --object-streams=generate --encrypt "" "" 256 -- base.pdf out.pdf` */
export const aes256_objstm = b64(
  'JVBERi0xLjcKJb/3ov4KMSAwIG9iago8PCAvRXh0ZW5zaW9ucyA8PCAvQURCRSA8PCAvQmFzZVZlcnNpb24gLzEuNyAvRXh0ZW5z' +
    'aW9uTGV2ZWwgOCA+PiA+PiAvTm90ZUhvbGRlciAzIDAgUiAvUGFnZXMgNCAwIFIgL1R5cGUgL0NhdGFsb2cgPj4KZW5kb2JqCjIg' +
    'MCBvYmoKPDwgL1R5cGUgL09ialN0bSAvTGVuZ3RoIDE2MCAvRmlsdGVyIC9GbGF0ZURlY29kZSAvTiAzIC9GaXJzdCAxNCA+Pgpz' +
    'dHJlYW0KphgrPtCkNPU2JrUI+BSTGs0eJAd9v+42T3n5vSEuUFPH8WtlZzMqF5l1cEbbqgmkDr5qq+U6rKWgRgCBE8doqiIorhJS' +
    'aYTXmJwVZlTyPWCxOEEdnj2al35e97alRyDtRLJ/w2fjK2Y5DwJ6BE4BFjiwuhpHpVfafcnbWv65Ji2SD2BcSzx9k6WW4+0V5J2k' +
    'bCaAE9dOtO/7uVYYgM67WmVuZHN0cmVhbQplbmRvYmoKNiAwIG9iago8PCAvRmlsdGVyIC9GbGF0ZURlY29kZSAvTGVuZ3RoIDgw' +
    'ID4+CnN0cmVhbQq4Uqq8bOT+CSS+BUJXzkMs4t4Gu72FAyhwpdJ53EOt3aq5moE71qCaXMHPyGgCXCbaqcLFXpFWiaK/9sNetWTZ' +
    'ZkIwnW5Y+NXn59jaJLaMuWVuZHN0cmVhbQplbmRvYmoKNyAwIG9iago8PCAvQ0YgPDwgL1N0ZENGIDw8IC9BdXRoRXZlbnQgL0Rv' +
    'Y09wZW4gL0NGTSAvQUVTVjMgL0xlbmd0aCAzMiA+PiA+PiAvRmlsdGVyIC9TdGFuZGFyZCAvTGVuZ3RoIDI1NiAvTyA8ZWMxNTVk' +
    'ODMxMjhhMjQzNjhjYWY2NGQxODQxYjM2ZGNjYTk4YjM5MTc4ZTc1MjA5MjIzMTlkOGYwZjA5NjIzZDJjMDQyMmU3OGQ1YWQ2OWRi' +
    'NTMxYTA3ZmZiM2EwMDMwPiAvT0UgPDc1YjQ3YjkyNzU5MzFhZmFjY2JmN2I2MTZiNTgyZTVjNTM1OTc4NTdhZmQzZThiOTUwMTFh' +
    'YTk4MjMxNjQ0Nzc+IC9QIC00IC9QZXJtcyA8NGZiNjQ4M2I5MDQzNzAwNGFmNmIyNTliYTIyMmY1ZmM+IC9SIDYgL1N0bUYgL1N0' +
    'ZENGIC9TdHJGIC9TdGRDRiAvVSA8NDEzNzQ0MWZmMTc4YWNkMmJhOWFhNjZmYzNjMzAwY2ZjZjk5YjY0NjA1OGRmNTExMWM1MWVk' +
    'YTQ3NDllMWVhYjBhZTI3NDMzMWUyY2U4ZWExNGJjMjA5MTIwZGI5Mjk1PiAvVUUgPDJkNjYxMTg3ZTc2MTJmNzc5ZTI3YzFiMzdk' +
    'MmNiNTI1MDQ0Y2Y0NzdkMjI5MTg4ZWJmMzM2M2Y2NjAwZmUyOTI+IC9WIDUgPj4KZW5kb2JqCjggMCBvYmoKPDwgL1R5cGUgL1hS' +
    'ZWYgL0xlbmd0aCA0MiAvRmlsdGVyIC9GbGF0ZURlY29kZSAvRGVjb2RlUGFybXMgPDwgL0NvbHVtbnMgNCAvUHJlZGljdG9yIDEy' +
    'ID4+IC9XIFsgMSAyIDEgXSAvUm9vdCAxIDAgUiAvU2l6ZSA5IC9JRCBbPGIzMmNkMTg0MTNiNzJiMjJmZDcwZWM3MjhjYWJlMjMx' +
    'PjxjOTI2NTA3NmE4YmNjYTY1YjkyMGE4ZTlkM2Q1Y2JlZD5dIC9FbmNyeXB0IDcgMCBSID4+CnN0cmVhbQp4nGNiAAImRgZ+BiYG' +
    'hlYQKw/EYmCEEP8Zp/1jYmCcBhRjUmYAAEUcBGkKZW5kc3RyZWFtCmVuZG9iagpzdGFydHhyZWYKMTEwNQolJUVPRgo=',
);
